when@dev:
    nelmio_api_doc:
        documentation:
            info:
                title: 'HealthCheck API'
                description: '1PT Test API'
                version: '%env(string:API_VERSION)%'
        areas: # to filter documented areas
            path_patterns:
                - ^/(?!api/(doc|doc\.json)$) # Accepts routes under /api except /api/doc
when@local:
    nelmio_api_doc:
        documentation:
            info:
                title: 'HealthCheck API'
                description: '1PT Test API'
                version: '%env(string:API_VERSION)%'
        areas: # to filter documented areas
            path_patterns:
                - ^/(?!api/(doc|doc\.json)$) # Accepts routes under /api except /api/doc
